### ISSUE TITLE
Hello,I have a question with method of decryptUnicodeStr.

### ISSUE THREAD

**Issue by deedywu** [Brenterino/jwzlib#4]
Sorry,my English is very pool,may be you can not understand my mean,you can use Google translator to translate my Chinese below.
I parsed wz file of 'String.wz' in CMS v079, I got a garbled Chinese code,The good news is that the English parameters are ok.Can you help me solve this problem. happy everyday :)
首先感到抱歉，我的英文不怎么样，也许你看上面我写的话不能明白我的意思.你可以使用翻译工具。
我解析CMS 079版本的String.wz文件，非常糟糕的是我得到的中文是乱码，但是英文的参数都没问题，你可以帮我修复这个问题吗，祝你每天开心：）

**Comment by Brenterino** [comment]
Greetings,

Could you provide a sample String.wz and some examples of what you are expecting to see versus what you are seeing?

You can also try using commit 92afb74b8cfbedac353a9c3d8024be8151b85460 and see if that changes anything.

Thanks!

Edit:  Could you also try the most recent version of JWzLib?  We had a contributor provide some modifications to the routine that decrypts unicode strings. Thanks!

**Comment by deedywu** [comment]
Thank you for answer my question,
I cloned your project 2 days ago,It's latest.
I uploaded file named String.wz and another named TestString.java ,  [click here](https://github.com/deedywu/CMS079),
Here is a screenshot of my test method,Thanks!
![image](https://user-images.githubusercontent.com/29275153/74603010-bc00ea00-50e9-11ea-9de7-c664c73dedca.png)

**Comment by deedywu** [comment]
Hello,
I had a edit just like [WzTools](https://github.com/flwmxd/WzTools/blob/master/WzReader.cpp)（line 187）.
In this way, I can get a few correct words, although most of them are still wrong.
Thanks！

![image](https://user-images.githubusercontent.com/29275153/74603909-8d880c80-50f3-11ea-834f-2a708fad24eb.png)



            byte[] bytes = readBytes(strLength * 2);
            return decryptUnicodeStr(bytes, strLength * 2);



    private String decryptUnicodeStr(byte[] bytes, int len) {
        int factor = 0xaaaa;
        char[] chars = new char[len];
        for (int index = 0; index < len; index = index + 2, ++factor) {
            char r = (char) (((bytes[index + 1] ^ key[index + 1] ^ (factor >> 0x08)) << 0x08) + (bytes[index] ^ key[index] ^ (factor & 0xff)));
            chars[index] = r;
        }
        return new String(chars);
    }

**Comment by Arnuh** [comment]
700000000: 羢鸾宫入勣
700000100: 羢鸾殿
700000101: 婤星殿
700000200: 媴客堂

Are these correct? Harepacker might give incorrect strings too. If this is correct the fix is to turn the `byte[] unicodeKey` into `char[] unicodeKey` and make sure any usages also use char.

**Comment by deedywu** [comment]
> 700000000: 羢鸾宫入勣
> 700000100: 羢鸾殿
> 700000101: 婤星殿
> 700000200: 媴客堂
> 
> Are these correct? Harepacker might give incorrect strings too. If this is correct the fix is to turn the `byte[] unicodeKey` into `char[] unicodeKey` and make sure any usages also use char.


Thanks,but these are garbled Chinese words.
And HaRepacker is right,because it's the same as in the game .
The correct ones are as follows，
700000000: 红鸾宫入口
700000100: 红鸾殿
700000101: 孤星殿
700000200: 宴客堂
Thanks.
